const Yargs = require('yargs')

Yargs(process.argv.slice(2), process.cwd())
  .version()
  .command(require('./cmds/db2csv'))
  .command(require('./cmds/klarna2json'))
  .command(require('./cmds/json2csv'))
  .demandCommand()
  .help()
  .showHelpOnFail(true)
  .wrap(Yargs.terminalWidth() !== null ? Yargs.terminalWidth() : 80)
  .parse()
